/* Mỗi phần tử là một lý do — bạn có thể sửa / thêm cho riêng Mai Ly */
window.LOVE_REASONS = [
  "Nụ cười của mình làm cả ngày anh nhẹ hơn.",
  "Mình lắng nghe anh — kể cả những lúc anh chẳng nói gì.",
  "Cách mình gọi anh là 'mình'.",
  "Mình mạnh mẽ theo cách rất riêng, rất đẹp.",
  "Những buổi tối im lặng bên mình cũng đủ đầy.",
  "Mình khiến anh muốn trở thành phiên bản tốt hơn của chính mình.",
  "Ánh mắt mình khi vui — anh nhớ mãi.",
  "Mình nhớ những điều nhỏ mà anh tưởng chẳng ai để ý.",
  "Cái cách mình cười khẽ khi xấu hổ.",
  "Mình tin anh, ngay cả khi anh chưa tin nổi bản thân.",
  "Mỗi tin nhắn của mình đều làm anh thấy được chọn.",
  "Mình dịu dàng với thế giới — và đặc biệt dịu dàng với anh.",
  "Những ước mơ của mình khiến anh muốn đi cùng thật xa.",
  "Mình biến những ngày bình thường thành kỷ niệm.",
  "Cái ôm của mình chữa lành nhiều hơn lời nói.",
  "Mình thẳng thắn, và anh trân trọng điều đó.",
  "Khi mình vui, cả bầu trời trong anh sáng lên.",
  "Mình kiên nhẫn với những vụng về của anh.",
  "Giọng nói của mình là giai điệu anh muốn nghe mãi.",
  "Mình dạy anh rằng yêu là chọn nhau mỗi ngày.",
  "Những sở thích kỳ lạ của mình khiến anh thấy dễ thương vô cùng.",
  "Mình hiện diện — đủ gần, đủ ấm, đủ thật.",
  "Cách mình chăm sóc người mình thương.",
  "Mình khiến anh dám nói ra những điều từng sợ.",
  "Kỷ niệm với mình là những vì sao anh mang theo.",
  "Mình không hoàn hảo — và anh yêu đúng con người đó.",
  "Ở bên mình, anh thấy tương lai có hình dạng rõ ràng hơn.",
  "Và lý do cuối: vì mình là Mai Ly — tình yêu của anh.",
];
